apiVersion: v1 
kind: Pod 
metadata:
  name: private-image-test-12
spec:
  containers:
    - name: uses-private-image
      image: svaddaram/paragraphanalyzer:latest
      imagePullPolicy: Always
  imagePullSecrets: 
    - name: regcred
      
